---
title: Helen Suter Jewelry
email: hello@helensuter.studio
description: >- # this means to ignore newlines until "baseurl:"
  Online Jewelry Shop for Helen Suter's Work
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  products:
    title: Products
    output: true

plugins:
  - jekyll-seo-tag
  - jemoji
  - jekyll-feed
